### ISSUE TITLE
Multiple "status" fields in CTML format

### ISSUE THREAD

**Issue by cmonnom** [dfci/matchengine-V2#10]
There are multiple entries for "status" in CTML but the types are not compatible.
Following the description of the metadata here: https://matchminer.gitbook.io/matchminer/deployment/ctml-and-trial-curation#metadata 
 ```javascript
"_summary": {
    "status": [
      {
        "value": "open to accrual"
      }
    ]
...
```
status is an array.

But several examples on the same page have status as a string (and not inside _summary):
https://matchminer.gitbook.io/matchminer/deployment/ctml-and-trial-curation#json-example
```javascript
{
  # Metadata 
  "protocol_no": "10-002",
  "status": "open to accrual",
  
  # Step, arm and dose information
  "treatment_list": {
    "step": [
      {
...
```

**Comment by ethansiegl** [comment]
Sorry for the delayed update, but this issue should now be resolved. by default, the engine will look for a `status` key which has the value `open to accrual` as the indicator of whether or not a trial is open for accrual. 

This option is also configurable via the `config.json` file if there are additional statuses which indicate an open status. There's more documentation on this here - https://app.gitbook.com/@matchminer/s/matchminer/matchengine-v2/engine-configuration-docs#global-configurations
